version: 2
jobs:
  build_app:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - app

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    steps:
      - run: npm run build
      - run: zip -r qrl-offline-wallet.zip dist
      - run: sudo npm install -g semantic-release
      - run:
          name: "Publish Release on GitHub"
          command: semantic-release

  build_cy:
    working_directory: ~/app
    docker:
      - image: cypress/browsers:chrome67
    steps:
      - checkout
      # find compatible cache from previous build,
      # it should have same dependencies installed from package.json checksum
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  1x-electron:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    steps:
      # restore application and Cypress binary before running the test command
      - attach_workspace:
          at: ~/
      - run:
          command: npm run test:e2e
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

workflows:
  version: 2
  main:
    jobs:
      - build_app
      - build_cy:
          requires:
            - build_app
      - 1x-electron:
          requires:
            - build_cy
      - deploy:
          requires:
            - build_app
            - 1x-electron
